# Generated by Django 4.1.2 on 2022-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'moderator'), (3, 'client')], default=1),
            preserve_default=False,
        ),
    ]
