# Generated by Django 4.1.2 on 2022-12-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'admin'), (2, 'moderator'), (3, 'client')], null=True),
        ),
    ]
