# Generated by Django 4.1.2 on 2022-12-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='usr',
            new_name='user',
        ),
    ]
