# Generated by Django 4.1.2 on 2022-12-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_usr_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='img',
        ),
    ]
